apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minecraft-monitor
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: minecraft
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: metrics
    interval: 15s