apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: default
spec:
  serviceName: "minecraft"
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java21
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 9225   # Porta de métricas
          name: metrics
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "PAPER"
        - name: MEMORY
          value: "5G"
        - name: MOTD
          value: "Servidor GitOps do Lucas"
        
        # --- CONFIGURAÇÃO DA WHITELIST ---
        - name: WHITELIST
          value: "CardosoBrB"
        - name: ENFORCE_WHITELIST
          value: "TRUE"

        # --- CORREÇÃO DO MONITORAMENTO (Modrinth) ---
        # Em vez de link fixo que quebra, pedimos pelo nome do projeto
        - name: MODRINTH_PROJECTS
          value: "minecraft-prometheus-exporter"
        
        # Ativa o plugin na porta correta
        - name: PROMETHEUS_EXPORTER_ENABLE
          value: "true"
        - name: PROMETHEUS_EXPORTER_PORT
          value: "9225"

        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data