apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: default
spec:
  serviceName: "minecraft"
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java21
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 9225   # Porta de métricas
          name: metrics
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "PAPER"
        - name: MEMORY
          value: "4G"           # 4G para sobrar RAM pro Monitoramento
        - name: MOTD
          value: "GitOps Monitorado"
        
        # Plugin Automático via Modrinth
        - name: MODRINTH_PROJECTS
          value: "minecraft-prometheus-exporter"
        
        - name: PROMETHEUS_EXPORTER_ENABLE
          value: "true"
        - name: PROMETHEUS_EXPORTER_PORT
          value: "9225"

        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data