apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: default
spec:
  serviceName: "minecraft"
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java21
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 9940   # <--- MUDE AQUI PARA 9940
          name: metrics
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "PAPER"
        - name: MEMORY
          value: "10G"
        - name: MOTD
          value: "Servidor GitOps Monitorado"
        
        # Link direto para a versão v3.0.0 (Isso está perfeito)
        - name: PLUGINS
          value: "https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.0.0/minecraft-prometheus-exporter-3.0.0.jar"
        
        - name: WHITELIST
          value: "CardosoBrB"
        - name: ENFORCE_WHITELIST
          value: "TRUE"

        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data