apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: default
spec:
  serviceName: "minecraft"
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java21
        ports:
        - containerPort: 25565
          name: minecraft
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "PAPER"
        
        # Já que você pagou pela máquina de 16GB, vamos dar 10GB pro jogo!
        - name: MEMORY
          value: "10G"
        
        - name: MOTD
          value: "Servidor GitOps Profissional"
        
        # --- MONITORAMENTO (Modrinth) ---
        - name: MODRINTH_PROJECTS
          value: "minecraft-prometheus-exporter"
        
        - name: PROMETHEUS_EXPORTER_ENABLE
          value: "true"
        - name: PROMETHEUS_EXPORTER_PORT
          value: "9225"
        
        # Mantendo sua Whitelist (Isso é importante)
        - name: WHITELIST
          value: "CardosoBrB"
        - name: ENFORCE_WHITELIST
          value: "TRUE"

        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data